### ISSUE TITLE
Card color

### ISSUE THREAD

**Issue by scheinerman** [charleskawczynski/PlayingCards.jl#10]
Hi Charles,

I don't feel comfortable editing your code because I might change things you don't want changed (and I might introduce bugs). So I'll use this Issues section to make suggestions. First one is that I'd like to see a `color` function. Here's a quick way to implement that I think is consistent with your package design. 

I'd like this feature because in solitaire games one often builds piles with alternating colors.

Thanks, 
Ed
<hr>

Add this:
```
export RedSuit, BlackSuit, color

"""
`color(C::Card)` returns `BlackSuit` if the card is a 
club or spade, and returns `RedSuit` is it's a heart or 
a diamond.
"""
function color(C::Card)
    return supertype(typeof(suit(C)))
end
```

Example:
```
julia> C = 5♠
5♠

julia> color(C)
BlackSuit
```

**Comment by scheinerman** [comment]
PS The name `color` might be too common in packages. Maybe `card_color` would be better?

**Comment by charleskawczynski** [comment]
One advantage of using `color` Is that we could define it both for a card and for a suit 🙂. `color` might be common, but I don’t think we’ll have any name collisions in this package. If it happens downstream we could always qualify names. I’m fine either way. What did you use originally?

**Comment by scheinerman** [comment]
Using `color` is fine for me. That's what I had in my package. Mine returned a `Symbol`, either `:red` or `:black`. I think that you'd prefer to return `BlackSuit` or `RedSuit`. Either is fine by me. 

If "some day" you have the energy or interest, you can add jokers. That'll be tricky because they don't have a suit, but they do have colors. I think there's a red joker and a black one in a standard deck. Thanks Charles!

**Comment by charleskawczynski** [comment]
Also, regarding

> I don't feel comfortable editing your code because I might change things you don't want changed (and I might introduce bugs)

We all write bugs, that's what code review is for 🙂. Feel free to open PRs and add me as a reviewer. We've got [bors](https://bors.tech/) hooked up, so CI can't break (barring race conditions) without changing the repo settings.

**Comment by charleskawczynski** [comment]
It looks like the color isn't used in very many flow-control contexts in FreeCell.jl, so I've just made `color` return a `Symbol` as you had it before--it's a bit simpler since we then only need two internal types rather than four (two of which would need to be exported).
