### ISSUE TITLE
Would you like riffle and cut?

### ISSUE THREAD

**Issue by scheinerman** [charleskawczynski/PlayingCards.jl#15]
Hi Charles,

First, thanks for your offer to help with `FreeCell`, but please see my comments there responding to the two issues you raised. I would like to understand docs and coverage for some of my _other_ packages and would welcome your assistance.

Now to the main point:

I tested my `cut` and `riffle` functions on your implementation of `PlayingCards` and they work fine. Do you want to include this functionality? If so, you can just copy the file 
[shuffle.jl ](https://github.com/scheinerman/PlayingCards52.jl/blob/master/src/shuffle.jl)
to your `src` directory and add the line `include("shuffle.jl")` to `PlayingCards.jl`. 

Ed

**Comment by charleskawczynski** [comment]
Sounds good. 

I looked into adding `riffle` and `cut`, but it looks like it depends on `binom_rv`. I see this uses `SimpleRandom.jl`/`Distributions.jl`. `Distributions.jl` has quite a few dependencies, and I'm wondering if we should keep its deps on the short side `PlayingCards.jl` and leave `PlayingCards.jl` to be responsible for only defining the types.

What's the use-case of  `riffle` and `cut`?

**Comment by scheinerman** [comment]
I have an alternative implementation of `riffle` that doesn't rely on those tools. But the use case is thin: People tend to do a poor job shuffling, and they often don't shuffle enough. They'll (say) three rounds of cut/riffle and then deal. That gives a mediocre randomization of the deck. If one wanted to study that, the GSR riffle shuffle is a reasonable model. That said, it's doubtful it'd get much use. 

There's a cool magic trick in which the magician gives a brand new deck of cards to an audience member. The magician never touches the deck, but tells the spectator to cut the deck, look at the top card and place it into the middle of the deck. Then cut and riffle the deck twice. The magician then takes the deck and figures out the card. The "magic" is that it's not hard to spot the card that's way out of place. 

But I doubt all that is worth adding this to the package.

**Comment by charleskawczynski** [comment]
Ah, ok, good to know. How does the existing `shuffle!` fair? I'd be happy to add a light-weight dependency implementation of `riffle`. Is the implementation on a remote repo--can you point me to the alternate implementation?

The magic trick sounds really cool! 😄
